openapi: 3.0.0
info:
  title: Albums API
  description: CRUD for albums
  version: 0.0.1
servers:
  - url: http://localhost:8080/v1
    description: Local server
paths:
  /albums:
    get:
      summary: Returns a list of albums.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':
          description: A JSON array of albums
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /albums/{albumId}:
    get:
      summary: Returns a album by id.
      parameters:
        - name: albumId
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type : integer
            format: int64
            minimum: 1
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':
          description: A JSON album item
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /users:
    post:
      summary: Creates a albums.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                artist:
                  type: string
                price:
                  type: string
      responses: 
        '201':
          description: Created
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string